### PR TITLE
Added support for B450M Bazooka Plus and fixed reversed lights issue

### LINKED ISSUE #39: Add B450M Bazooka Plus to supported devices list
This works perfectly with the motherboard (https://www.msi.com/Motherboard/B450M-BAZOOKA-PLUS.html).

Just the starting not supported message is annoying every time I open it. Also, is there any reference for the API? I'm planning on making a universal app for MysticLight, SteelSeries Engine and other lighting apps.

### PR DESCRIPTION
**Pull request by FadedCoder**
Fixes #39 . Support for #37 can be added by adding the motherboard version to the list of `reversed_mbs`.

### CODE REVIEW

**Comment by ixjf** [comment]
I don't know if I'm satisfied with the way you handle motherboards that work differently (i.e. the way it's designed), but I don't know if I want to jump into that hole just yet. This does work for now but it could get messy later on if other people decide to follow the same design to support their motherboards. I'll take a look into this at some point later, if you don't mind.

**Comment by ixjf** [comment]
Also curious to know why colours are reversed in these motherboards and if there are other things that are different.

**Comment by FadedCoder** [comment]
> Also curious to know why colours are reversed in these motherboards and if there are other things that are different.

I have absolutely no idea. Even the official MSI Mystic Lights app reverses the colour. Everything else seems to be fine, atleast for now.

**Comment by FadedCoder** [comment]
> I'll take a look into this at some point later, if you don't mind.

Sure, fine by me. Haven't programmed in this sector for a while, so it can probably be implemented in a better way.

**Comment by ixjf** [comment]
Can you confirm that this build fixes the issue?

[Release.zip](https://github.com/ixjf/MSIRGB/files/5080741/Release.zip)

**Comment by ixjf** [comment]
Fixed in 2.3.0.

**Pull request closed without merging**
